In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int64')

In [4]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [5]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [6]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)

In [7]:
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [8]:
b.dtype

dtype('float64')

In [9]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [10]:
np.zeros((3,3),'d')

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
np.empty((4,4),'d')

array([[  0.00000000e+000,   0.00000000e+000,   1.77863633e-322,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  2.12215770e-314,   1.97626258e-323,   0.00000000e+000,
          0.00000000e+000]])

In [12]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.random.standard_normal((2,4))

array([[ 1.23440627, -0.39035196,  0.18185496,  1.56869647],
       [ 0.74160254,  0.15619149,  0.79453644, -0.65878599]])

In [15]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[ 1.26328274, -1.90693522,  0.00379105],
       [-0.37768188, -0.34070629, -1.31688553],
       [-1.66929909,  0.82002641, -0.45799134],
       [-0.03446812,  0.11392679,  2.6503177 ]])

In [16]:
np.hstack([a,b])

array([[ 1.26328274, -1.90693522,  0.00379105, -1.66929909,  0.82002641,
        -0.45799134],
       [-0.37768188, -0.34070629, -1.31688553, -0.03446812,  0.11392679,
         2.6503177 ]])

In [17]:
a.transpose()

array([[ 1.26328274, -0.37768188],
       [-1.90693522, -0.34070629],
       [ 0.00379105, -1.31688553]])

In [18]:
np.save('example.npy',a)

In [19]:
a1 = np.load('example.npy')

In [20]:
a1

array([[ 1.26328274, -1.90693522,  0.00379105],
       [-0.37768188, -0.34070629, -1.31688553]])