In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [8]:
vv = np.random.random((5,4))

In [9]:
vv

array([[ 0.09137921,  0.77700747,  0.39884184,  0.30716753],
       [ 0.61637695,  0.20001582,  0.023984  ,  0.24829491],
       [ 0.87007385,  0.55486179,  0.52878119,  0.9913901 ],
       [ 0.40446365,  0.57444187,  0.77248462,  0.2901253 ],
       [ 0.25235129,  0.1354475 ,  0.68302613,  0.84045052]])

In [10]:
vv[0,0]

0.091379213907519685

In [11]:
vv[4,3]

0.84045051592923137

In [12]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
ll[1,2]

TypeError: list indices must be integers, not tuple

In [14]:
ll[1][2]

6

In [15]:
v[2:4]

array([ 5. ,  7.5])

In [16]:
vv[2:5,1]

array([ 0.55486179,  0.57444187,  0.1354475 ])

In [17]:
vv[2:5,1:2]

array([[ 0.55486179],
       [ 0.57444187],
       [ 0.1354475 ]])

In [18]:
vv[2:-1,:]

array([[ 0.87007385,  0.55486179,  0.52878119,  0.9913901 ],
       [ 0.40446365,  0.57444187,  0.77248462,  0.2901253 ]])

In [20]:
vv[:,::2]

array([[ 0.09137921,  0.39884184],
       [ 0.61637695,  0.023984  ],
       [ 0.87007385,  0.52878119],
       [ 0.40446365,  0.77248462],
       [ 0.25235129,  0.68302613]])

In [21]:
v2 = v[2:4]

In [22]:
v2[0] = 0

In [23]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [24]:
v3 = v[2:4].copy()

In [25]:
v3[0] = 1

In [26]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [27]:
v[[1,2,3]]

array([ 2.5,  0. ,  7.5])

In [29]:
bool_index = v > 0

In [30]:
v[bool_index]

array([  2.5,   7.5,  10. ])

In [31]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [32]:
vv

array([[ 0.09137921,  1.55401495,  0.39884184,  0.30716753],
       [ 1.2327539 ,  0.20001582,  0.023984  ,  0.24829491],
       [ 1.74014769,  1.10972357,  1.05756237,  1.98278021],
       [ 0.40446365,  1.14888374,  1.54496924,  0.2901253 ],
       [ 0.25235129,  0.1354475 ,  1.36605225,  1.68090103]])